name: Reusable Workflow Caller

on:
    workflow_dispatch:

jobs:
    call-reusable-workflow:
      name: Invoke reuseable workflow with relative path
      uses: ./.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yml
      with:
        foo: "Hello from the caller workflow!"
        environment: staging
      secrets: inherit
    
    call-reusable-workflow-sha:
        name: Invoke reuseable workflow with repo + commit hash
        uses: yohames/ghActions/.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yml@a9c408a61137660789ff04267c76fecc57dd479b
        with:
          foo: "Hello! from the caller workflow using a specific commit SHA!"
          environment: Dev
        secrets: 
            DEV_SECRET: ${{ secrets.DEV_SECRET }}
