name: Passing Data

on:
    workflow_dispatch:

jobs:
    producer:
        runs-on: ubuntu-latest
        outputs:
            foo: ${{ steps.producer-step-1.outputs.foo }}
        steps:
            - name: Set output
              id: producer-step-1
              run: echo "foo=bar" >> "$GITHUB_OUTPUT"
    consumer:
        runs-on: ubuntu-latest
        needs: producer
        steps:
            - name: Get output
              id: consumer-step-1
              run: |
                  echo "foo from producer: ${{ needs.producer.outputs.foo }}"
