name: Secrets and Variables
on:
    workflow_dispatch:

jobs:
    staging-deploy:
        runs-on: ubuntu-latest
        environment: Dev
        env:
            STAGING_ENV_VARIABLE: ${{ vars.DEV_ENV }}
            STAGING_ENV_SECRET: ${{ secrets.DEV_SECRET }}
        steps:
            - name: Print secrets and variables in staging-deploy
              run: |
                  echo "=== staging-deploy environment variables and secrets ==="
                  echo "✅STAGING_ENV_VARIABLE: $STAGING_ENV_VARIABLE"
                  echo "✅STAGING_ENV_SECRET: $STAGING_ENV_SECRET"
                  echo "🦶STAGING_ENV_SECRET: ${{ secrets.DEV_SECRET }}"
                  echo "🦶STAGING_ENV_VARIABLE: ${{ vars.DEV_ENV }}"
        
