name: Run TypeScript Linter Formatter and Builder

on: [push]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run Ts action
        uses: ./06-authoring-actions/ts-action
    #   - name: Install dependencies
    #     run: pnpm install
    #   - name: Run linter and formatter
    #     run: pnpm run lint && pnpm run format
    #   - name: Build the action
    #     run: npm run build
